### ISSUE TITLE
배너 생성 이후 배너 삭제 불가

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/plugin-banner#10]
배너를 생성한 이후, 특정 배너를 삭제 하고 싶을때 관리자 사이트의 배너 관리에서 삭제할 수 없는것 같습니다.
삭제할 수 있는 방법이 있나요?

![image](https://user-images.githubusercontent.com/47233861/54097081-e6362c00-43f1-11e9-978e-5f3b5a7ef6b9.png)

**Comment by junnaa** [comment]
*논의/결정 필요한 사항*
- 등록된 아이템이 있는 경우에도 삭제 가능하게 할 것인지?
- 해당 배너 위젯을 사용하고 있는 모듈, 페이지가 있는 경우에는 어떻게 처리할 것인지?

*UI*
- [아이템 관리] [위젯코드] [설정] [삭제] 순으로 버튼 추가
